const frases = [
    "Há tempo para cada coisa, o relógio de Deus é perfeito!",
    "Você faz suas escolhas, e suas escolhas fazem você.",
    "Nunca desista daquilo que você não passa um dia sem pensar.",
    "A soma de pequenos vacilos pode causar grandes estragos.",
    "Fique sempre preparado para uma decepção. As pessoas são piores do que você imagina.",
    "As pessoas esquecerão o que você disse, as pessoas esquecerão o que você fez, \nmas elas nunca esquecerão como você as faz sentir!",
    "Você nunca sabe da força que tem até que a sua única opção é ser forte.",
    "Tome cuidado com o vazio de uma vida ocupada demais.",
    "Sem o primeiro passo não existe caminhada.",
    "Quando você não tiver mais tempo, você vai ver porque ele é tão valioso.",
    "Vale mais a pena ser melhor do que ontem do que ser melhor que o outro.",
    "Os baixos da vida nos ensinam o que os altos não poderiam!",
    "O agora não é para sempre!",
    "Pode não dar certo por mil razões, mas que não seja por falta de tentar.",
    "Quando a mente não muda, os erros se repetem.",
    "Ame como se o mundo estivesse acabando. Ele está.",
    "A gentileza é o jeito mais bonito de ser o sol no dia nublado de alguém!",
    "Muitas pessoas tentam te desmotivar porque é nítido o medo que elas têm \nde você chegar onde elas não chegaram.",
    "Mesmo que ninguém veja, faça seu melhor todos os dias.",
    "Se custar a paz, já custou caro demais.",
    "Não importa quão devagar você vá, contando que você não pare!",
    "É sobre saber dar valor ao que não tem preço.",
    "Foca no degrau à tua frente e não na escada inteira...",
    "Algumas vezes na vida a gente precisa passar por momentos ruins \npara manter os bons em perspectiva.",
    "Nem sempre você recebe aquilo que dá. Mas você só dá aquilo que é.",
    "Tudo que temos enfrentado é a preparação para viver tudo aquilo que sempre sonhamos.",
    "Hoje em dia ninguém quer tentar nada, a fila de troca é a mais rápida.",
    "Carência cria afetos imaginários.",
    "Onde quer que você esteja, esteja por inteiro!",
    "O maior fracasso é nunca tentar.",
    "Enquanto houver vontade de lutar, sempre haverá chance de vencer.",
    "Preocupação não muda o futuro, apenas tira a paz do presente.",
    "Não se trata de ter todas as respostas, mas sim de estar aberto a todas as perguntas.",
    "As maiores conquistas muitas vezes vêm de superar os maiores desafios.",
    "O fracasso não é o oposto do sucesso, é parte dele!",
    "O passado é um lugar de referência, não de residência.",
    "A verdadeira sabedoria está em reconhecer a própria ignorância.",
    "Às vezes as perguntas são complicadas e as respostas são simples.",
    "A única coisa que pode controlar é você mesmo. Mudar sua atitude é uma escolha. \nNão importa o que aconteça, você sempre terá controle sobre o modo como você responde.",
    "A maior riqueza não enche os bolsos, enche a alma.",
    "Se você aceita perder, você não pode ganhar.",
    "Se não puder fazer tudo, faça o que puder!",
    "Nós somos o que repetidamente fazemos. A excelência, portanto, não é um feito, mas um hábito.",
    "Intensidade só faz mal quando o outro é superficial.",
    "O tempo é a moeda mais valiosa que você possui. Gaste-o sabiamente.",
    "Às vezes é preciso se perder para se encontrar.",
    "O fracasso é apenas a oportunidade de recomeçar de uma forma mais inteligente.",
    "A vida é uma aventura ousada ou não é nada.",
    "O maior erro que você pode cometer é o de ficar o tempo todo com medo de cometer algum.",
    "O verdadeiro heroísmo consiste em persistir por mais um momento, quando tudo parece perdido.",
    "Quando sentir que tudo está contra você, lembre-se de que o avião decola contra o vento, não a favor dele.",
    "Vencedores nunca desistem, e quem desiste nunca vence.",
    "Perdoar é um ato de coragem.",
    "Não importa quantas vezes você caia, o que importa é quantas vezes você se levanta!",
    "Persista, insista e nunca desista, pois a vitória pode estar logo adiante.",
    "O verdadeiro sucesso não é sobre vencer os outros, mas sobre superar a si mesmo.",
    "Não se preocupe com o que as pessoas pensam de você, elas estão \nocupadas demais preocupadas com o que você pensa delas.",
    "O único lugar onde o sucesso vem antes do trabalho é no dicionário.",
    "A maior glória em viver não está em nunca cair, mas em nos levantarmos \ncada vez que caímos.",
    "Fazer o certo é mais eficiente do que falar de quem fez errado.",
    "A aceitação não significa que você concorda com tudo, \nsignifica que você está disposto a aceitar a realidade e seguir em frente.",
    "Coragem não é a ausência do medo, mas sim a determinação de seguir em frente apesar dele!",
    "Quando fugimos dos problemas, eles não deixam de existir.",
    "O amor não é uma necessidade e sim uma escolha.",
    "A raiva é um ladrão que rouba os momentos bons."
];


function mudarFrase() {
  const i = Math.floor(Math.random() * frases.length);
  const novaFrase = frases[i];    
  
  document.getElementById("caixa-texto").innerHTML = novaFrase;
}

document.getElementById("button-container").addEventListener("click", mudarFrase);